const asset = (fileName: string) => new URL(`../assets/images/${fileName}`, import.meta.url).href;

export const mockCategories = [
  {
    id: '1',
    name: 'Women',
    slug: 'women',
    image_url: asset('cover (1).jpg'),
    parent_id: null,
  },
  {
    id: '2',
    name: 'Accessories',
    slug: 'accessories',
    image_url: asset('bag (1).jpg'),
    parent_id: null,
  },
  {
    id: '3',
    name: 'Luxury Collection',
    slug: 'luxury-collection',
    image_url: asset('shoes (1).jpg'),
    parent_id: null,
  },
  {
    id: '4',
    name: 'Sale',
    slug: 'sale',
    image_url: asset('acc (4).jpg'),
    parent_id: null,
  },
  {
    id: '5',
    name: 'New Arrivals',
    slug: 'new-arrivals',
    image_url: asset('hero-model.png'),
    parent_id: null,
  },
];

export const mockProducts = [
  {
    id: 'prod_1',
    name: 'Linen Blend Blazer',
    slug: 'linen-blend-blazer',
    base_price: 89.0,
    sale_price: 69.0,
    images: [
      asset('tops (1).jpg'),
      asset('tops (2).jpg'),
    ],
    rating: 5,
    review_count: 128,
    stock_quantity: 18,
    category_id: '1',
    is_featured: true,
    is_trending: true,
    created_at: '2026-07-24T10:00:00.000Z',
    description: 'A refined linen blend blazer with a relaxed silhouette — perfect for elevating everyday looks.',
    sku: 'LBB-001',
    specifications: {
      benefits: ['Breathable linen blend', 'Relaxed fit', 'Machine washable'],
      material: 'Linen & cotton blend',
      color: 'Sand',
    },
  },
  {
    id: 'prod_2',
    name: 'Classic White Shirt',
    slug: 'classic-white-shirt',
    base_price: 45.0,
    sale_price: null,
    images: [
      asset('tops (3).jpg'),
      asset('tops (4).jpg'),
    ],
    rating: 5,
    review_count: 96,
    stock_quantity: 26,
    category_id: '1',
    is_featured: true,
    is_trending: false,
    created_at: '2026-06-18T08:30:00.000Z',
    description: 'A crisp, timeless white shirt crafted from premium cotton for effortless style.',
    sku: 'CWS-002',
    specifications: {
      benefits: ['Premium cotton', 'Classic collar', 'Easy to style'],
      material: '100% cotton',
      color: 'White',
    },
  },
  {
    id: 'prod_3',
    name: 'High-Waist Trousers',
    slug: 'high-waist-trousers',
    base_price: 65.0,
    sale_price: 52.0,
    images: [
      asset('dress (3).jpg'),
      asset('dress (4).jpg'),
    ],
    rating: 5,
    review_count: 84,
    stock_quantity: 11,
    category_id: '1',
    is_featured: true,
    is_trending: true,
    created_at: '2026-07-02T11:15:00.000Z',
    description: 'Tailored high-waist trousers with a flattering cut and comfortable stretch.',
    sku: 'HWT-003',
    specifications: {
      benefits: ['High-waist fit', 'Stretch fabric', 'Side pockets'],
      material: 'Polyester blend',
      color: 'Charcoal',
    },
  },
  {
    id: 'prod_4',
    name: 'Silk Midi Dress',
    slug: 'silk-midi-dress',
    base_price: 120.0,
    sale_price: null,
    images: [
      asset('dress (5).jpg'),
      asset('dress (1).jpg'),
    ],
    rating: 5,
    review_count: 72,
    stock_quantity: 82,
    category_id: '3',
    is_featured: true,
    is_trending: false,
    created_at: '2026-06-10T13:00:00.000Z',
    description: 'An elegant silk midi dress with a fluid drape for day-to-night versatility.',
    sku: 'SMD-004',
    specifications: {
      benefits: ['Pure silk', 'Midi length', 'Effortless drape'],
      material: '100% silk',
      color: 'Champagne',
    },
  },
  {
    id: 'prod_5',
    name: 'Leather Crossbody Bag',
    slug: 'leather-crossbody-bag',
    base_price: 95.0,
    sale_price: 76.0,
    images: [
      asset('bag (1).jpg'),
      asset('bag (2).jpg'),
    ],
    rating: 5,
    review_count: 156,
    stock_quantity: 120,
    category_id: '2',
    is_featured: true,
    is_trending: false,
    created_at: '2026-07-28T17:45:00.000Z',
    description: 'A sleek leather crossbody bag with adjustable strap and gold hardware.',
    sku: 'LCB-005',
    specifications: {
      benefits: ['Genuine leather', 'Adjustable strap', 'Interior pockets'],
      material: 'Leather',
      color: 'Tan',
    },
  },
  {
    id: 'prod_6',
    name: 'Cashmere Sweater',
    slug: 'cashmere-sweater',
    base_price: 150.0,
    sale_price: 138.0,
    images: [
      asset('tops (5).jpg'),
      asset('tops (6).jpg'),
    ],
    rating: 5,
    review_count: 203,
    stock_quantity: 9,
    category_id: '1',
    is_featured: true,
    is_trending: true,
    created_at: '2026-07-05T12:00:00.000Z',
    description: 'A luxuriously soft cashmere sweater in a relaxed, timeless silhouette.',
    sku: 'CSW-006',
    specifications: {
      benefits: ['100% cashmere', 'Relaxed fit', 'Lightweight warmth'],
      material: 'Cashmere',
      color: 'Camel',
    },
  },
  {
    id: 'prod_7',
    name: 'Crystal Heel Sandals',
    slug: 'crystal-heel-sandals',
    base_price: 72.0,
    sale_price: 54.0,
    images: [
      asset('shoes (1).jpg'),
      asset('shoes (2).jpg'),
    ],
    rating: 4.5,
    review_count: 39,
    stock_quantity: 54,
    category_id: '5',
    is_featured: false,
    is_trending: true,
    created_at: '2026-08-01T09:00:00.000Z',
    description: 'Sparkling sandals with crystal embellishments and a comfortable heel.',
    sku: 'CHS-007',
    specifications: {
      benefits: ['Padded footbed', 'Adjustable buckle', 'High-shine crystals'],
      material: 'Leather & crystals',
      color: 'Champagne',
    },
  },
  {
    id: 'prod_8',
    name: 'Cashmere Travel Wrap',
    slug: 'cashmere-travel-wrap',
    base_price: 150.0,
    sale_price: null,
    images: [
      asset('acc (3).jpg'),
      asset('acc (4).jpg'),
    ],
    rating: 4.9,
    review_count: 72,
    stock_quantity: 34,
    category_id: '1',
    is_featured: false,
    is_trending: false,
    created_at: '2026-07-12T14:20:00.000Z',
    description: 'A luxurious cashmere wrap ideal for travel and adding warmth to your evening look.',
    sku: 'CTW-008',
    specifications: {
      benefits: ['Lightweight warmth', 'Soft finish', 'Easy to style'],
      material: '100% cashmere',
      color: 'Stone',
    },
  },
  {
    id: 'prod_9',
    name: 'Satin Slip Dress',
    slug: 'satin-slip-dress',
    base_price: 138.0,
    sale_price: 104.0,
    images: [
      asset('dress (2).jpg'),
      asset('dress (3).jpg'),
    ],
    rating: 4.7,
    review_count: 88,
    stock_quantity: 27,
    category_id: '3',
    is_featured: true,
    is_trending: true,
    created_at: '2026-08-01T10:00:00.000Z',
    description: 'A fluid satin slip dress designed for effortless evening elegance.',
    sku: 'SSD-009',
    specifications: {
      benefits: ['Lightweight satin', 'Bias cut', 'Adjustable straps'],
      material: 'Satin',
      color: 'Champagne',
    },
  },
  {
    id: 'prod_10',
    name: 'Statement Chain Earrings',
    slug: 'statement-chain-earrings',
    base_price: 42.0,
    sale_price: 32.0,
    images: [
      asset('acc (5).jpg'),
      asset('acc (6).jpg'),
    ],
    rating: 4.6,
    review_count: 61,
    stock_quantity: 74,
    category_id: '2',
    is_featured: false,
    is_trending: true,
    created_at: '2026-07-20T12:20:00.000Z',
    description: 'Bold chain earrings with a polished finish for standout styling.',
    sku: 'SCE-010',
    specifications: {
      benefits: ['Hypoallergenic plating', 'Lightweight design', 'Secure clasp'],
      material: 'Gold-plated brass',
      color: 'Gold',
    },
  },
  {
    id: 'prod_11',
    name: 'Platform Sandals',
    slug: 'platform-sandals',
    base_price: 110.0,
    sale_price: 92.0,
    images: [
      asset('shoes (3).jpg'),
      asset('shoes (4).jpg'),
    ],
    rating: 4.8,
    review_count: 54,
    stock_quantity: 36,
    category_id: '3',
    is_featured: false,
    is_trending: true,
    created_at: '2026-07-28T16:00:00.000Z',
    description: 'Chic platform sandals with a modern silhouette and comfortable cushioning.',
    sku: 'PS-011',
    specifications: {
      benefits: ['Soft footbed', 'Tapered heel', 'Adjustable buckle'],
      material: 'Leather',
      color: 'Black',
    },
  },
  {
    id: 'prod_12',
    name: 'Day-to-Night Jumpsuit',
    slug: 'day-to-night-jumpsuit',
    base_price: 98.0,
    sale_price: 78.0,
    images: [
      asset('cover (2).jpg'),
      asset('cover (3).jpg'),
    ],
    rating: 4.9,
    review_count: 110,
    stock_quantity: 42,
    category_id: '1',
    is_featured: true,
    is_trending: false,
    created_at: '2026-08-03T14:40:00.000Z',
    description: 'A versatile jumpsuit that moves easily from daytime workwear to evening events.',
    sku: 'DNJ-012',
    specifications: {
      benefits: ['Stretch crepe', 'Cinched waist', 'Wide-leg fit'],
      material: 'Polyester blend',
      color: 'Midnight blue',
    },
  },
  {
    id: 'prod_13',
    name: 'Embellished Evening Clutch',
    slug: 'embellished-evening-clutch',
    base_price: 68.0,
    sale_price: 52.0,
    images: [
      asset('bag (3).jpg'),
      asset('bag (4).jpg'),
    ],
    rating: 4.7,
    review_count: 65,
    stock_quantity: 38,
    category_id: '2',
    is_featured: false,
    is_trending: true,
    created_at: '2026-08-04T09:20:00.000Z',
    description: 'A polished evening clutch with subtle sparkle and a chain strap for elegant events.',
    sku: 'EEC-013',
    specifications: {
      benefits: ['Chain strap', 'Velvet lining', 'Compact essentials fit'],
      material: 'Faux leather',
      color: 'Ivory',
    },
  },
  {
    id: 'prod_14',
    name: 'Velvet Ballet Flats',
    slug: 'velvet-ballet-flats',
    base_price: 82.0,
    sale_price: 64.0,
    images: [
      asset('shoes (5).jpg'),
      asset('shoes (6).jpg'),
    ],
    rating: 4.8,
    review_count: 53,
    stock_quantity: 24,
    category_id: '3',
    is_featured: false,
    is_trending: false,
    created_at: '2026-07-30T11:10:00.000Z',
    description: 'Soft velvet ballet flats finished with a delicate bow and cushioned footbed.',
    sku: 'VBF-014',
    specifications: {
      benefits: ['Cushioned sole', 'Padded interior', 'Classic silhouette'],
      material: 'Velvet',
      color: 'Plum',
    },
  },
  {
    id: 'prod_15',
    name: 'Sheer Lace Camisole',
    slug: 'sheer-lace-camisole',
    base_price: 48.0,
    sale_price: 36.0,
    images: [
      asset('tops (1).jpg'),
      asset('dress (1).jpg'),
    ],
    rating: 4.6,
    review_count: 42,
    stock_quantity: 50,
    category_id: '1',
    is_featured: false,
    is_trending: false,
    created_at: '2026-08-01T12:00:00.000Z',
    description: 'An ultra-feminine lace camisole that layers beautifully under jackets or on its own.',
    sku: 'SLC-015',
    specifications: {
      benefits: ['Delicate lace trim', 'Lightweight fabric', 'Adjustable straps'],
      material: 'Silk blend',
      color: 'Rose',
    },
  },
  {
    id: 'prod_16',
    name: 'Leather Tote Bag',
    slug: 'leather-tote-bag',
    base_price: 128.0,
    sale_price: 99.0,
    images: [
      asset('bag (5).jpg'),
      asset('bag (6).jpg'),
    ],
    rating: 4.9,
    review_count: 84,
    stock_quantity: 29,
    category_id: '2',
    is_featured: true,
    is_trending: false,
    created_at: '2026-08-02T14:30:00.000Z',
    description: 'A roomy leather tote with structured lines and interior pockets for daily carry.',
    sku: 'LTB-016',
    specifications: {
      benefits: ['Structured design', 'Interior phone pocket', 'Magnetic closure'],
      material: 'Leather',
      color: 'Stone',
    },
  },
  {
    id: 'prod_17',
    name: 'Tailored Wool Coat',
    slug: 'tailored-wool-coat',
    base_price: 220.0,
    sale_price: 178.0,
    images: [
      asset('cover (4).jpg'),
      asset('cover (1).jpg'),
    ],
    rating: 4.8,
    review_count: 72,
    stock_quantity: 15,
    category_id: '1',
    is_featured: true,
    is_trending: true,
    created_at: '2026-07-25T09:00:00.000Z',
    description: 'A polished wool coat with sharp tailoring and timeless appeal for cooler weather.',
    sku: 'TWC-017',
    specifications: {
      benefits: ['Wool blend', 'Structured shoulders', 'Warm lining'],
      material: 'Wool blend',
      color: 'Charcoal',
    },
  },
  {
    id: 'prod_18',
    name: 'Statement Hoop Earrings',
    slug: 'statement-hoop-earrings',
    base_price: 34.0,
    sale_price: 24.0,
    images: [
      asset('acc (6).jpg'),
      asset('acc (7).jpg'),
    ],
    rating: 4.5,
    review_count: 67,
    stock_quantity: 84,
    category_id: '2',
    is_featured: false,
    is_trending: true,
    created_at: '2026-07-22T10:15:00.000Z',
    description: 'Bold hammered hoop earrings that elevate any outfit with subtle shine.',
    sku: 'SHE-018',
    specifications: {
      benefits: ['Lightweight wear', 'Polished finish', 'Secure latch'],
      material: 'Gold-plated brass',
      color: 'Gold',
    },
  },
  {
    id: 'prod_19',
    name: 'Satin Pajama Set',
    slug: 'satin-pajama-set',
    base_price: 68.0,
    sale_price: 54.0,
    images: [
      asset('dress (2).jpg'),
      asset('cover (3).jpg'),
    ],
    rating: 4.7,
    review_count: 96,
    stock_quantity: 60,
    category_id: '1',
    is_featured: false,
    is_trending: true,
    created_at: '2026-08-05T08:00:00.000Z',
    description: 'Luxurious satin pajamas designed for comfort and a stylish night’s sleep.',
    sku: 'SPS-019',
    specifications: {
      benefits: ['Soft satin', 'Elastic waistband', 'Matching top and bottom'],
      material: 'Satin',
      color: 'Blush',
    },
  },
  {
    id: 'prod_20',
    name: 'Monochrome Slip Skirt',
    slug: 'monochrome-slip-skirt',
    base_price: 58.0,
    sale_price: 44.0,
    images: [
      asset('dress (4).jpg'),
      asset('dress (5).jpg'),
    ],
    rating: 4.6,
    review_count: 81,
    stock_quantity: 30,
    category_id: '1',
    is_featured: false,
    is_trending: false,
    created_at: '2026-07-29T11:44:00.000Z',
    description: 'A sleek slip skirt with a minimalist silhouette that transitions from casual to refined.',
    sku: 'MSS-020',
    specifications: {
      benefits: ['Bias cut', 'Lightweight fabric', 'Comfort stretch'],
      material: 'Silk blend',
      color: 'Black',
    },
  },
  {
    id: 'prod_21',
    name: 'Gold Cuff Bracelet',
    slug: 'gold-cuff-bracelet',
    base_price: 38.0,
    sale_price: 28.0,
    images: [
      asset('acc (1).jpg'),
      asset('acc (2).jpg'),
    ],
    rating: 4.4,
    review_count: 39,
    stock_quantity: 99,
    category_id: '2',
    is_featured: false,
    is_trending: false,
    created_at: '2026-07-18T13:00:00.000Z',
    description: 'A polished cuff bracelet with a modern finish and comfortable fit for every occasion.',
    sku: 'GCB-021',
    specifications: {
      benefits: ['Open cuff design', 'Polished surface', 'Adjustable sizing'],
      material: 'Gold-plated metal',
      color: 'Gold',
    },
  },
  {
    id: 'prod_22',
    name: 'Silk Scarf',
    slug: 'silk-scarf',
    base_price: 42.0,
    sale_price: 34.0,
    images: [
      asset('cover (1).jpg'),
      asset('hero-model.png'),
    ],
    rating: 4.5,
    review_count: 74,
    stock_quantity: 80,
    category_id: '2',
    is_featured: false,
    is_trending: true,
    created_at: '2026-08-04T16:25:00.000Z',
    description: 'A statement silk scarf finished with a vibrant print to elevate any outfit.',
    sku: 'SS-022',
    specifications: {
      benefits: ['Pure silk', 'Hand-rolled edges', 'Versatile styling'],
      material: 'Silk',
      color: 'Multicolor',
    },
  },
  {
    id: 'prod_23',
    name: 'Sequin Party Top',
    slug: 'sequin-party-top',
    base_price: 68.0,
    sale_price: 54.0,
    images: [
      asset('dress (1).jpg'),
      asset('tops (3).jpg'),
    ],
    rating: 4.7,
    review_count: 51,
    stock_quantity: 22,
    category_id: '3',
    is_featured: false,
    is_trending: true,
    created_at: '2026-08-01T18:05:00.000Z',
    description: 'A dazzling sequin cami that adds instant glamour to party looks.',
    sku: 'SPT-023',
    specifications: {
      benefits: ['Sequin embellishment', 'Slim fit', 'Lined interior'],
      material: 'Polyester blend',
      color: 'Silver',
    },
  },
  {
    id: 'prod_24',
    name: 'Chic Suede Booties',
    slug: 'chic-suede-booties',
    base_price: 140.0,
    sale_price: 118.0,
    images: [
      asset('shoes (7).jpg'),
      asset('shoes (1).jpg'),
    ],
    rating: 4.8,
    review_count: 46,
    stock_quantity: 18,
    category_id: '3',
    is_featured: true,
    is_trending: false,
    created_at: '2026-07-28T19:10:00.000Z',
    description: 'Soft suede booties with a sculpted heel and refined ankle silhouette.',
    sku: 'SSB-024',
    specifications: {
      benefits: ['Suede upper', 'Padded insole', 'Side zipper'],
      material: 'Suede',
      color: 'Navy',
    },
  },
  {
    id: 'prod_25',
    name: 'Luxe Cashmere Hat',
    slug: 'luxe-cashmere-hat',
    base_price: 58.0,
    sale_price: 44.0,
    images: [
      asset('acc (2).jpg'),
      asset('acc (4).jpg'),
    ],
    rating: 4.6,
    review_count: 32,
    stock_quantity: 61,
    category_id: '2',
    is_featured: false,
    is_trending: false,
    created_at: '2026-07-26T20:00:00.000Z',
    description: 'A soft cashmere hat with a cozy fit and luxurious texture for colder days.',
    sku: 'LCH-025',
    specifications: {
      benefits: ['Soft cashmere', 'Warm fit', 'Fold-over cuff'],
      material: 'Cashmere',
      color: 'Beige',
    },
  },
  {
    id: 'prod_26',
    name: 'Printed Midi Dress',
    slug: 'printed-midi-dress',
    base_price: 110.0,
    sale_price: 88.0,
    images: [
      asset('dress (5).jpg'),
      asset('cover (2).jpg'),
    ],
    rating: 4.8,
    review_count: 79,
    stock_quantity: 45,
    category_id: '1',
    is_featured: true,
    is_trending: true,
    created_at: '2026-08-02T13:10:00.000Z',
    description: 'A feminine midi dress in a bold print for easy daytime style.',
    sku: 'PMD-026',
    specifications: {
      benefits: ['Flowy fit', 'Adjustable waist', 'Breathable fabric'],
      material: 'Viscose blend',
      color: 'Floral',
    },
  },
  {
    id: 'prod_27',
    name: 'Structured Blazer Dress',
    slug: 'structured-blazer-dress',
    base_price: 132.0,
    sale_price: 108.0,
    images: [
      asset('cover (1).jpg'),
      asset('tops (4).jpg'),
    ],
    rating: 4.7,
    review_count: 54,
    stock_quantity: 26,
    category_id: '3',
    is_featured: false,
    is_trending: true,
    created_at: '2026-07-24T17:40:00.000Z',
    description: 'A polished blazer dress with sharp tailoring and a modern hemline.',
    sku: 'SBD-027',
    specifications: {
      benefits: ['Sharp tailoring', 'Double-breasted front', 'Structured shoulders'],
      material: 'Wool blend',
      color: 'Charcoal',
    },
  },
  {
    id: 'prod_28',
    name: 'Pearl Hair Clip Set',
    slug: 'pearl-hair-clip-set',
    base_price: 26.0,
    sale_price: 18.0,
    images: [
      asset('acc (7).jpg'),
      asset('bag (3).jpg'),
    ],
    rating: 4.6,
    review_count: 47,
    stock_quantity: 96,
    category_id: '2',
    is_featured: false,
    is_trending: false,
    created_at: '2026-08-03T11:50:00.000Z',
    description: 'A set of pearl hair clips to add sparkle and polish to any hairstyle.',
    sku: 'PHC-028',
    specifications: {
      benefits: ['Set of 3', 'Pearl detail', 'Strong grip'],
      material: 'Metal & faux pearls',
      color: 'Pearl white',
    },
  },
  {
    id: 'prod_29',
    name: 'Bouclé Mini Bag',
    slug: 'boucle-mini-bag',
    base_price: 78.0,
    sale_price: 62.0,
    images: [
      asset('bag (4).jpg'),
      asset('acc (1).jpg'),
    ],
    rating: 4.5,
    review_count: 39,
    stock_quantity: 48,
    category_id: '2',
    is_featured: false,
    is_trending: true,
    created_at: '2026-07-30T07:50:00.000Z',
    description: 'A textured mini bag with chain detail and a compact shape for city outings.',
    sku: 'BMB-029',
    specifications: {
      benefits: ['Bouclé fabric', 'Chain strap', 'Interior pocket'],
      material: 'Bouclé',
      color: 'Ivory',
    },
  },
  {
    id: 'prod_30',
    name: 'Tailored Shorts',
    slug: 'tailored-shorts',
    base_price: 48.0,
    sale_price: 37.0,
    images: [
      asset('tops (2).jpg'),
      asset('dress (3).jpg'),
    ],
    rating: 4.6,
    review_count: 63,
    stock_quantity: 53,
    category_id: '1',
    is_featured: false,
    is_trending: true,
    created_at: '2026-07-23T15:20:00.000Z',
    description: 'High-rise tailored shorts with a clean finish and versatile styling options.',
    sku: 'TS-030',
    specifications: {
      benefits: ['High-rise fit', 'Side pockets', 'Crisp finish'],
      material: 'Polyester blend',
      color: 'Sand',
    },
  },
  {
    id: 'prod_31',
    name: 'Ribbed Knit Dress',
    slug: 'ribbed-knit-dress',
    base_price: 62.0,
    sale_price: 50.0,
    images: [
      asset('tops (5).jpg'),
      asset('tops (6).jpg'),
    ],
    rating: 4.7,
    review_count: 82,
    stock_quantity: 44,
    category_id: '1',
    is_featured: true,
    is_trending: true,
    created_at: '2026-08-04T09:35:00.000Z',
    description: 'A form-fitting ribbed knit dress designed for comfort and everyday polish.',
    sku: 'RKD-031',
    specifications: {
      benefits: ['Stretch knit', 'Midi length', 'Soft feel'],
      material: 'Cotton blend',
      color: 'Cream',
    },
  },
  {
    id: 'prod_32',
    name: 'Cropped Denim Jacket',
    slug: 'cropped-denim-jacket',
    base_price: 88.0,
    sale_price: 70.0,
    images: [
      asset('cover (4).jpg'),
      asset('cover (2).jpg'),
    ],
    rating: 4.8,
    review_count: 91,
    stock_quantity: 37,
    category_id: '1',
    is_featured: true,
    is_trending: false,
    created_at: '2026-08-03T11:10:00.000Z',
    description: 'A modern cropped denim jacket with a flattering fit for day or night looks.',
    sku: 'CDJ-032',
    specifications: {
      benefits: ['Cropped silhouette', 'Button front', 'Front pockets'],
      material: 'Denim',
      color: 'Indigo',
    },
  },
];

export const mockReviews = [
  {
    id: 'review_1',
    product_id: 'prod_1',
    rating: 5,
    title: 'Perfect everyday blazer',
    comment: 'This blazer is so versatile and the linen blend keeps me comfortable all day.',
    verified_purchase: true,
    created_at: '2026-07-26T10:00:00.000Z',
    user_profiles: { full_name: 'Marina K.' },
  },
  {
    id: 'review_2',
    product_id: 'prod_3',
    rating: 5,
    title: 'Great fit and quality',
    comment: 'The high-waist cut is flattering and the fabric feels premium. Very happy.',
    verified_purchase: true,
    created_at: '2026-07-10T15:48:00.000Z',
    user_profiles: { full_name: 'Janelle P.' },
  },
  {
    id: 'review_3',
    product_id: 'prod_6',
    rating: 5,
    title: 'Worth every cedi',
    comment: 'The softest cashmere I have ever owned. Warm but not bulky.',
    verified_purchase: true,
    created_at: '2026-08-02T09:15:00.000Z',
    user_profiles: { full_name: 'Nia A.' },
  },
  {
    id: 'review_4',
    product_id: 'prod_5',
    rating: 4,
    title: 'Beautiful bag',
    comment: 'Great quality leather and the perfect size for everyday use.',
    verified_purchase: false,
    created_at: '2026-07-30T18:22:00.000Z',
    user_profiles: { full_name: 'Maya R.' },
  },
];
